version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - VIRTUAL_ENV=envname
    command: sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"

